 (cd "$(git rev-parse --show-toplevel)" && git apply --3way <<'EOF' 
diff --git a/prisma.config.ts b/prisma.config.ts
index 8ded1a58d5249e565046f6e8b57bab1a718d1a74..cb9732d01a2c0aab56dd5df1398a3ec8937e70ba 100644
--- a/prisma.config.ts
+++ b/prisma.config.ts
@@ -1,16 +1,18 @@
 
 // This file was generated by Prisma and assumes you have installed the following:
 // npm install --save-dev prisma dotenv
 import "dotenv/config";
-import { defineConfig, env } from "prisma/config";
+import { defineConfig } from "prisma/config";
+
+const databaseUrl = process.env.DATABASE_URL ?? "file:./dev.db";
 
 export default defineConfig({
   schema: "prisma/schema.prisma",
   migrations: {
     path: "prisma/migrations",
   },
   engine: "classic",
   datasource: {
-    url: env("DATABASE_URL"),
+    url: databaseUrl,
   },
 });
 
EOF
)
